puts "🌱 Seeding spices..."

# Seed your database here

puts "Creating furnitures..."
Furniture.create(name: "Sculptural Customizable Sectional", space_category: "Living", image_link: "https://media.restorationhardware.com/is/image/rhis/prod27510221_E21218502451_F_CC?&illum=0&$np-fullwidth-md$")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Living", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Dining", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Bed", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Office", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")
Furniture.create(name: "", space_category: "Decor", image_link: "")

puts "✅ Done seeding!"
